config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'
  
  resources :calorie_entries
  get 'profile' => 'profile#index'
  get 'profile/edit' => 'profile#edit'
  get 'profile/stats' => 'profile#stats'
  patch 'profile/update' => 'profile#update' 

end

app/models/calorie_entry.rb
class CalorieEntry < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :calorie_entries
  
  def calories_today
    self.calorie_entries.where("date >= ?", Time.zone.now.to_date).sum(:num_calories)
  end
  
  def calorie_entries_today
    self.calorie_entries.where("date >= ?", Time.zone.now.to_date).order(date: :desc)
  end
  
  def calorie_entries_last_7_days
    self.calorie_entries.where("date >= ?", (Time.zone.now - 7.days).to_date).order(date: :desc)
  end
  
  def calorie_entries_last_x_days(num_days, dir=:desc)
    self.calorie_entries.where("date >= ?", (Time.zone.now - num_days.days).to_date).order(date: dir)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  around_filter :set_time_zone
  force_ssl

  def set_time_zone(&block)
    time_zone = current_user.try(:time_zone) || 'UTC'
    Time.use_zone(time_zone, &block)
  end
end

app/controllers/calorie_entries_controller.rb
class CalorieEntriesController < ApplicationController
    before_action :authenticate_user!
    def index
        @calorie_entries = current_user.calorie_entries.order(date: :desc).paginate(:page => params[:page], :per_page => 30)
    end
    
    def show
    end
    
    def new
        @calorie_entry = CalorieEntry.new
        # @calorie_entry.date = Time.now
    end
    
    def create
        if calorie_entry_params[:num_calories].empty? or calorie_entry_params[:date].empty?
            @calorie_entry = CalorieEntry.new
            # @calorie_entry.date = calorie_entry_params[:date].in_time_zone("UTC")
            @calorie_entry.num_calories = calorie_entry_params[:num_calories]
            flash.now[:danger] = "Please fill out all fields."
            render 'new'
        else
            @calorie_entry = CalorieEntry.new(calorie_entry_params)
            @calorie_entry.user = current_user
            if @calorie_entry.save
                flash[:success] = "Entry saved successfully."
                redirect_to root_path
            else
                flash.now[:danger] = "Something went wrong."
                render 'new'
            end
        end
    end
    
    def destroy
        CalorieEntry.find(params[:id]).destroy
        flash[:success] = "Entry deleted."
        redirect_to root_path
    end
    
    private
    def calorie_entry_params
        params.require(:calorie_entry).permit(:num_calories, :user_id, :date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @calorie_entries = current_user.calorie_entries_today.order(date: :desc).paginate(:page => params[:page], :per_page => 10)
    end
    
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!
    
  def index
  end
  
  def edit
  end
    
  def update
    if current_user.update_attributes(profile_params)
    # Handle a successful update.
      redirect_to profile_path
    else
      render 'edit'
    end
  end
  
  def stats
    @num_days = params[:days] ? params[:days].to_f : 7
    @max = 0
    calorie_entries = current_user.calorie_entries_last_x_days(@num_days, :asc)
    @calorie_goal = current_user.calorie_goal
    @calorie_goal_data = {}
    @calorie_data = {}
    calorie_entries.each do |calorie_entry|
      calorie_entry_date = calorie_entry.date.strftime("%b %d, %Y")
      # calorie_entry_date = calorie_entry.date.midnight
      if not @calorie_data[calorie_entry_date]
        @calorie_data[calorie_entry_date] = 0
      end
      @calorie_data[calorie_entry_date] += calorie_entry.num_calories
      @max = @calorie_data[calorie_entry_date] > @max ? @calorie_data[calorie_entry_date] : @max
      @calorie_goal_data[calorie_entry_date] = @calorie_goal
    end
    
  end
    
  private

    def profile_params
      params.require(:user).permit(:calorie_goal, :time_zone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

# Add to config/initializers/form.rb or the end of app/helpers/application_helper.rb
module ActionView
  module Helpers
    class FormBuilder 
      def date_select(method, options = {}, html_options = {})
        existing_date = @object.send(method) 

        # Set default date if object's attr is nil
        existing_date ||= Time.now.to_date

        formatted_date = existing_date.to_date.strftime("%F") if existing_date.present?
        @template.content_tag(:div, :class => "input-group") do    
          text_field(method, :value => formatted_date, :class => "form-control datepicker", :"data-date-format" => "YYYY-MM-DD") +
          @template.content_tag(:span, @template.content_tag(:span, "", :class => "glyphicon glyphicon-calendar") ,:class => "input-group-addon")
        end
      end

      def datetime_select(method, options = {}, html_options = {})
        existing_time = @object.send(method)

        # Set default date if object's attr is nil
        existing_time ||= Time.now

        formatted_time = existing_time.to_time.strftime("%F %I:%M %p") if existing_time.present?
        @template.content_tag(:div, :class => "input-group") do    
          text_field(method, :value => formatted_time, :class => "form-control datetimepicker", :"data-date-format" => "YYYY-MM-DD hh:mm A") +
          @template.content_tag(:span, @template.content_tag(:span, "", :class => "glyphicon glyphicon-calendar") ,:class => "input-group-addon")
        end
      end
    end
  end
end

app/helpers/calorie_entries_helper.rb
module CalorieEntriesHelper
end

app/helpers/calorie_entry_controller_helper.rb
module CalorieEntryControllerHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/calorie_entries/_entries.html.erb
<%= will_paginate @calorie_entries, :renderer => BootstrapPagination::Rails %>
<table class="table table-striped table-bordered table-hover">
  <thead>
   <tr>
      <th>Date</th>
      <th>Calories</th>
      <th></th>
    </tr> 
  </thead>
  <tbody>
    <% @calorie_entries.each do |calorie_entry| %>
    <tr>
      <td><%= calorie_entry.date.to_s(:long_ordinal) %></td>
      <td><%= calorie_entry.num_calories %></td>
      <td><%= link_to 'Delete', calorie_entry, :method => :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
    <tr>
      <td><%= link_to 'New entry', new_calorie_entry_path %></td>
      <td></td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/calorie_entries/create.html.erb
<p>calories_entries</p>

app/views/calorie_entries/index.html.erb
<%= render 'calorie_entries/entries' %>

app/views/calorie_entries/new.html.erb
<p>Log new entry:</p>
<%= form_for @calorie_entry, url: calorie_entries_path do |f| %>
  <div class="form-group">
    <%= f.label :num_calories %><br/>
    <%= f.number_field :num_calories, :min => 0, :required => true %><br/>
    <%= f.label :date ,:required => true %><br/>
    <%= f.date_select :date %>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= @formatted_time %>

app/views/calorie_entries/show.html.erb
<p>calories_entries</p>

app/views/home/index.html.erb
<% if current_user.try(:calorie_goal) != 0 %>
  <h4>Current amount:</h4>
  <%= render 'profile/calorie_goal' %>
<% end %>
<h4>Last 10 entries:</h4>
<%= render 'calorie_entries/entries' %>

app/views/layouts/_navbar.erb
<ul class="nav nav-tabs">
  <li role="presentation" <%= current_page?("/") ? "class=active" : "" %>><a href="/">Home</a></li>
  <li role="presentation" <%= current_page?("/calorie_entries") ? "class=active" : "" %>><a href="/calorie_entries">Entries</a></li>
  <li role="presentation" <%= current_page?("/profile/stats") ? "class=active" : "" %>><a href="/profile/stats">Stats</a></li>
  <% if user_signed_in? %>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        Profile <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <%= render 'devise/menu/login_items' %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calorie Tracker</title>
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render 'layouts/navbar' %>
    <div class="row-fluid">
      <% flash.each do |key, value| %>
        <% if value %>
          <% key = key == 'alert' ? 'danger' : key %>
          <% key = key == 'notice' ? 'info' : key %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      <% end %>
    </div>
    <div class="row-fluid">
      <%= yield %>
    </div>
  </div>
</body>
</html>